config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :users
  resources :events
  resources :dishes
  root 'welcome#index'

  get "/signup" => "users#new"
  get "/login"   => "sessions#new"
  post "/login"  => "sessions#create"
  delete "/logout"  => "sessions#destroy"

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  has_many :occasions
  has_many :events, through: :occasions
  has_many :attendees, through: :occasions, source: :attendee
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, class_name: 'User'
  has_many :occasions
  has_many :attendees, through: :occasions, source: :attendee
  has_many :dishes, through: :occasions

  validates :date, presence: true
end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
  belongs_to :attendee, class_name: "User"
  belongs_to :event
  belongs_to :dish
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :occasions, class_name: "Occasion", foreign_key: :attendee_id
  has_many :events, through: :occasions
  has_many :created_events, class_name: "Event", foreign_key: :creator_id
  has_many :dishes, through: :occasions

  validates_presence_of :username, :email
  validates_uniqueness_of :username, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  def current_user
    @_user || User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

  def new
    @user = User.find(current_user.id)
    @dish = Dish.new
  end

  def create
    @event = Event.find_by_title(params[:dish][:events])
    @dish = Dish.create(
      name: params[:dish][:name],
      course: params[:dish][:course],
      gluten_free: params[:dish][:gluten_free],
      )
      current_user.dishes << @dish
      @dish.events << @event
      redirect_to user_path(current_user)
  end

  def show
    @dish = Dish.find(params[:id])
    @events = @dish.events
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  respond_to :html, :js

  def index
    @events = Event.all.order('date DESC')
  end

  def new
    @event = Event.new
    render 'new'
  end

  def create
    @event = Event.new(event_params)
    @event.creator_id = current_user.id
    if @event.save
      @event.attendees << current_user
      redirect_to user_path(current_user)
    else
      @event.errors
      render "new"
    end
  end

  def edit
    @event = Event.find(params[:id])
    @event.attendees << current_user
    redirect_to user_path(params[:id])
  end

  def show
    @event = Event.find_by_id(params[:id])
    @dishes = @event.dishes
    @created_event = current_user.created_events.where(id: @event.id)
    @attending_event = current_user.events.where(id: @event.id)
  end

private
  def event_params
    params.require(:event).permit(:title, :description, :street_address, :city, :state, :zip, :date, :start_time)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new #login
    @user = User.new
  end

  def create #post login
    @user = User.find_by_email(params[:user][:email]).try(:authenticate, params[:user][:password])
    if @user
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      @user = User.new
      render "new"
    end
  end

  def destroy #logout
    session[:user_id] = nil
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      @user.errors
      render "new"
    end
  end

  def show
    @dishes = current_user.dishes.order(created_at: :desc).limit(5)
    @created_events = current_user.created_events
    @created_and_attending = current_user.events + current_user.created_events
  end

  private
    def user_params
      params.require(:user).permit(:username, :name, :email, :password, :password_confirmation)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/events_helper.rb
module EventsHelper
def us_states
  [
    ['AK', 'AK'],
    ['AL', 'AL'],
    ['AR', 'AR'],
    ['AZ', 'AZ'],
    ['CA', 'CA'],
    ['CO', 'CO'],
    ['CT', 'CT'],
    ['DC', 'DC'],
    ['DE', 'DE'],
    ['FL', 'FL'],
    ['GA', 'GA'],
    ['HI', 'HI'],
    ['IA', 'IA'],
    ['ID', 'ID'],
    ['IL', 'IL'],
    ['IN', 'IN'],
    ['KS', 'KS'],
    ['KY', 'KY'],
    ['LA', 'LA'],
    ['MA', 'MA'],
    ['MD', 'MD'],
    ['ME', 'ME'],
    ['MI', 'MI'],
    ['MN', 'MN'],
    ['MO', 'MO'],
    ['MS', 'MS'],
    ['MT', 'MT'],
    ['NC', 'NC'],
    ['ND', 'ND'],
    ['NE', 'NE'],
    ['NH', 'NH'],
    ['NJ', 'NJ'],
    ['NM', 'NM'],
    ['NV', 'NV'],
    ['NY', 'NY'],
    ['OH', 'OH'],
    ['OK', 'OK'],
    ['OR', 'OR'],
    ['PA', 'PA'],
    ['RI', 'RI'],
    ['SC', 'SC'],
    ['SD', 'SD'],
    ['TN', 'TN'],
    ['TX', 'TX'],
    ['UT', 'UT'],
    ['VA', 'VA'],
    ['VT', 'VT'],
    ['WA', 'WA'],
    ['WI', 'WI'],
    ['WV', 'WV'],
    ['WY', 'WY']
  ]
end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dishes/new.html.erb
<div class = "container">
  <h2>What will you bring?</h2>
  <%= form_for @dish do |f|  %>
    <div class="field">
      <%= f.label :name, "Name of dish: " %> <br />
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :course, "Course: " %> <br />
      <%= f.text_field :course %>
    </div>

    <div class="field">
      <%= f.label :gluten_free, "Gluten-free? " %> <br />
      <%= f.check_box :gluten_free %> <br /><br />
    </div>

    <div class="field">
      <%= f.label :event, "Events: " %> <br />
      <%= f.select "events", current_user.events.map {|event| [ event.title, event.title ] }, { prompt: "Select Potluck" } %>
    </div></br></br>

    <%= submit_tag "Make it.", id: "submit-new-meetup-btn",class: "btn btn-success" %>
  <% end %>
</div>

app/views/dishes/show.html.erb
 <div class="container">
  <div class="jumbotron">
    <h2>You're making: <%=@dish.name %></h2>
    <p>Events where this dish will be a hit: </p>
    <% @events.each do |event| %>
      <%= event.title%> on <%= event.date.strftime("%B %d, %Y") %>
    <% end %>
  </div>
</div>

app/views/events/_form.html.erb
<div class = "container">
  <div class="two-column">
  <h2>What will you bring?</h2>
  <%= form_for @dish do |f|  %>

    <div class="field">
      <%= f.label :name, "Name of dish: " %> </br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :course, "Course: " %> </br>
      <%= f.text_field :course %>
    </div>

    <div class="field">
      <%= f.label :gluten_free, "Gluten-free? " %> </br
       <%= f.check_box :gluten_free %> <br /></br>
    </div></br></br>

    <%= submit_tag "Make it.", id: "submit-new-meetup-btn",class: "btn btn-success" %>
  <% end %>
  <%= link_to image_tag("outdoor_potluck.jpg", :class => "outdoor-potluck"), user_path(current_user) %>
  </div>
</div>

app/views/events/index.html.erb
<div class = "container">
  <h3>All events</h3>
  <table class = "table table-condensed table-hover table-responsive">
    <tr class = "info">
      <th>Event</th>
      <th>Date</th>
    </tr>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.title, event_path(event) %> </td>
        <td><%=event.date.strftime("%B")%> <%=event.date.strftime("%d")%> </td>
    <% end %>
  </table>
      </tr>
</div>

app/views/events/new.html.erb
<div class = "container">
  <div class = "add-item">
    <h2>Add A New Potluck</h2>
    <%= form_for @event do |f| %>
      <p>
        <%= f.text_field :title, :cols => "30", :rows => "50", :placeholder => "Fancy Name" %>
      </p>

     <p>
      <%= f.text_field :street_address, :size => "30x10", :placeholder => "Street Address" %>
    </p>
    <p>
      <%= f.text_field :zip, :size => "30x10", :placeholder => "Zip Code" %>
    </p>

     <p>
      <%= f.date_field :date %>
    </p>

     <p>
      <%= f.text_field :start_time, :placeholder => "Start Time" %>
    </p>
    <p>
      <%= f.text_area :description, :size => "60x5", :placeholder => "Description" %>
    </p>

    <p>
       <%= submit_tag "Create It.", id: "submit-new-meetup-btn",class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/events/new.js.erb
$(".button-join").on('click', function(e) {
  e.preventDefault();
  $(".add-dish").append('<p>Response:</p>');
});

app/views/events/show.html.erb
<div class = "container">
   <h2>Hi <%= current_user.username %>.</h2>
      <div class="jumbotron">
        <h3>Potluck Deets for <%= @event.title %> on <%= @event.date.strftime("%B %d, %Y") %></h3>
        Start Time: <%= @event.start_time %> pm<br>
        Location:
          <li><%= @event.street_address %></li>
          <li><%= @event.city %> <%= @event.state %> <%= @event.zip %></li>

        Description: <%= @event.description %>
        <h4>Attendees:</h4>
        <ul>
          <% @dishes.each do |dish| %>
            <% dish.attendees.each do |attendee|%>
              <li><%= attendee.name %> is bringing <%= link_to dish.name, dish_path(dish) %></li>
            <% end %>
          <% end %>
        </ul>
        <% if @created_event.empty? && @attending_event.empty? %>
          <%= link_to "Join 'em!", edit_event_path(@event), class: "btn btn-success" %>
        <% end %>
          <%= link_to "Bring something.", new_dish_path, class:  "btn btn-success" %>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Potluck</title>

  <%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=Lora:400,700', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <div class="navbar-header">
          <% if current_user %>
           <%= link_to "Bring Chips.", welcome_index_path, :class => "navbar-brand" %>
          <% end %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li> <%= link_to "Hi, #{current_user.username.titleize}!", user_path(current_user.id) %></li>
            <li class="active"><%= link_to "Logout", logout_path, method: :delete %></li>
          <% else %>
            <li class="active"><%= link_to "Sign Up", signup_path %></li>
           <li class="active"><%= link_to "Login", login_path %></li>
         <% end %>
        </ul>
      </div>
    </div>
  </nav>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<body class ="no-background">
  <div class = "container">
    <div class="two-column">
      <%= form_for @user, :html => { class: "form-horizontal" } do |f| %>
        <legend>Sign Up</legend>
          <%if @user.errors.any?%>
            <h3>Hey! Sign up first. Then start potlucking.</h3>
              <%@user.errors.full_messages.each do |message|%>
                <p><%=message%></p>
              <%end%>
          <%end%>

      <div class="form-group">
        <%= f.label :username, class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :username, placeholder: "Username", class: "form-control", id: "inputUsername" %>
        </div>
      </div>

      <div class="form-group">
      <%= f.label :name, class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :name, class: "form-control", placeholder: "   none" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.email_field :email, placeholder: "Email", class: "form-control", id: "inputEmail" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password, class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.password_field :password, placeholder: "Password", class: "form-control", id: "inputPassword" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "form-control", id: "inputPasswordConfirmation" %><br>
        </div>
      </div>
      <%= f.submit value: 'Sign Up', class: "btn btn-primary" %><br>

      <% end %>
      <%= link_to image_tag("outdoor_potluck.jpg", :class => "outdoor-potluck"), welcome_index_path %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class = "user-form">
   <h2>Hi <%= current_user.username %>.</h2>
      <p><%= link_to "Add a potluck!", new_event_path, class: "btn btn-success"   %></p>
      <% if current_user.events.empty? %>
        <div class="jumbotron">
          <p>You have no upcoming potlucks scheduled. Get social and <%= link_to "join a potluck.", events_path %></p>
        </div>
      <% else %>
        <div class="row">
          <div class="col-xs-12 tile-container">
            <div class="jumbotron">
              <h3>Upcoming Potlucks</h3>
                <% current_user.events.each do |event| %>
                  <li><%= link_to event.title, event_path(event) %></li>
                <% end %>

                <%= link_to "Join more.", events_path, class: "btn btn-success"   %>
            </div>
          </div>
        </div>
      <% end %>
      <% if @created_and_attending.present? %>
        <div class="row">
          <div class="col-xs-12 tile-container">
            <div class="jumbotron">
              <h3>Dishes To Prepare:</h3>
                <% if @dishes.empty? %>
                  <p>You haven't signed up to cook anything yet? Get with it.</p>
                <% else %>
                  <% @dishes.each do |dish| %>
                    <li><%= link_to dish.name, dish_path(dish) %></li>
                  <% end %>
                <% end %></br>
                <p><%= link_to "Add Dish", new_dish_path, class: "btn btn-success"   %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% if @created_events %>
      <div class="row">
        <div class="col-xs-12 tile-container">
          <div class="jumbotron">
            <h3>Potlucks You've Created</h3>
              <% if @created_events.empty? %>
                <p><%= link_to "Start one up.", new_event_path , class: "btn btn-success"   %></p>
              <% else %>
                <% @created_events.each do |event| %>
                  <li><%= link_to event.title, event_path(event) %></li>
                <% end %>
              <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class = "container">
  <%= link_to image_tag("potluck.jpg", :class => "main-img") %>

  <div class = "form-inline">
    <%= form_for :user, url: '/users' do |f| %>
      <p>What are you bringing?</p>
      <%= f.text_field :password, :class => "form-text", :placeholder => " Killer Mac & Cheese" %>
      <%= f.submit "Go", :class => "sign-button" %>
    <% end %>
  </div>
</div>